@controller=http://localhost/almira/admin/paket

GET {{controller}}/get HTTP/1.1
Content-Type: application/json

###
POST {{controller}}/add HTTP/1.1
Content-Type: application/json

{
    "namapaket": "Weekend",
    "hargapaket": "1615000",
    "ketpaket": "Dengan SIM",
    "jumlahkali": "16",
    "durasiwaktu": "2 Jam"
}

###

PUT {{controller}}/update HTTP/1.1
Content-Type: application/json

{
  "idpaket": "1",
    "namapaket": "Reguler",
    "hargapaket": "1290000",
    "ketpaket": "Dengan Sim",
    "jumlahkali": "12",
    "durasiwaktu": "2 Jam"
}

###

DELETE {{controller}}/delete/3 HTTP/1.1