@controller=http://localhost/almira/admin/paket

GET {{controller}}/get HTTP/1.1
Content-Type: application/json

###
POST {{controller}}/add HTTP/1.1
Content-Type: application/json

{
    "namapaket": "Exclusiv",
    "hargapaket": "1500000",
    "ketpaket": "Dengan SIM",
    "jumlahkali": "12",
    "durasiwaktu": "2 Jam"
}

###

PUT {{controller}}/update HTTP/1.1
Content-Type: application/json

{
  "idpaket": "2",
  "namapaket": "Reguler",
  "hargapaket": "900000",
  "ketpaket": "Dengan SIM",
  "jumlahkali": "12",
  "durasiwaktu": "2 Jam"
}

###

DELETE {{controller}}/delete/3 HTTP/1.1