@controller=http://localhost/almira/admin/siswa

GET {{controller}}/get/9 HTTP/1.1
Content-Type: application/json

###
POST {{controller}}/add HTTP/1.1
Content-Type: application/json

{
  "idpaket": "2",
  "namasiswa": "a",
  "alamatsiswa": "a",
  "tempatlahir": "a",
  "tanggallahir": "2000-02-02",
  "email": "candra@mail.com",
  "notlpn": "082111",
  "password": "123456",
  "paket": {
      "idpaket": "2",
      "namapaket": "Reguler",
      "hargapaket": "900000",
      "ketpaket": "Dengan SIM",
      "jumlahkali": "12",
      "durasiwaktu": "2 Jam"
    },
  "roles": {
    "idrule": "2",
    "rule": "Siswa"
  }
}

###

PUT {{controller}}/update HTTP/1.1
Content-Type: application/json

{
  "idsiswa": "9",
  "idpaket": "2",
  "namasiswa": "Candra Putra Wicaksana",
  "alamatsiswa": "Perumahan Permata Indah",
  "tempatlahir": "Arso",
  "tanggallahir": "2000-02-02",
  "email": "candra@mail.com",
  "notlpn": "082111",
  "iduser": "14",
  "paket": {
    "idpaket": "2",
    "namapaket": "Reguler",
    "hargapaket": "900000",
    "ketpaket": "Dengan SIM",
    "jumlahkali": "12",
    "durasiwaktu": "2 Jam"
  },
  "pembayaran": null,
  "roles": {
    "idrule": "2",
    "rule": "Siswa"
  }
}

###

DELETE {{controller}}/delete/14 HTTP/1.1