@controller=http://localhost/almira/admin/staff

GET {{controller}}/get HTTP/1.1
Content-Type: application/json

###
POST {{controller}}/add HTTP/1.1
Content-Type: application/json

{
	"namastaf": "Deni Malik",
	"alamat": "Perumahan Penda II",
	"tlpn": "082238281801",
	"email": "denimalik207@mail.com",
	"password": "123456",
	"roles": {"idrule": 1}
}

###

PUT {{controller}}/update HTTP/1.1
Content-Type: application/json

{
  "idstaf": "1",
    "namastaf": "Deni Malik",
    "alamat": "Perumahan Penda II",
    "tlpn": "082238281801",
    "email": "denimalik207@mail.com",
    "iduser": "14",
    "password": "4e630c0ad1d9f329b2a7f34527e16b4b",
    "roles": {
      "idrule": "1",
      "rule": "admin"
  }
}

###

DELETE {{controller}}/delete/8 HTTP/1.1